version: '3'

services:
  db:
    environment:
      - POSTGRES_USER=${STOWDO_DB_USER}
      - POSTGRES_PASSWORD=${STOWDO_DB_PASSWORD}
      - POSTGRES_DB=${STOWDO_DB_NAME}
    hostname: "${STOWDO_DB_HOST}"
    image: postgres:14-alpine
    restart: unless-stopped
    user: root
    volumes:
      - ./db-data:/var/lib/postgresql/data

  minio:
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    hostname: "${MINIO_HOST}"
    image: bitnami/minio
    restart: unless-stopped
    volumes:
      - ./minio-data:/data

  api:
    command: >
      bash -c 'sleep 5; python /app/manage.py migrate; python /app/manage.py runserver 0.0.0.0:8000;'
    depends_on:
      - db
    environment:
      - MINIO_HOST
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - STOWDO_SECRET_KEY
      - STOWDO_ENVIRONMENT
      - STOWDO_DB_HOST
      - STOWDO_DB_PORT
      - STOWDO_DB_USER
      - STOWDO_DB_PASSWORD
    image: "redbeandock/stowdo-backend:${STOWDO_VERSION}"
    restart: unless-stopped

  app:
    depends_on:
      - api
    environment:
      - NODE_ENV
      - REACT_APP_STOWDO_VERSION
      - REACT_APP_STOWDO_API_HOST
      - REACT_APP_STOWDO_API_PORT
      - REACT_APP_STOWDO_API_PROTOCOL
    image: "redbeandock/stowdo-frontend:${REACT_APP_STOWDO_VERSION}"
    restart: unless-stopped

  api_lb:
    image: nginx:latest
    volumes:
      - ./nginx-config/api-lb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/api-lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: unless-stopped

  app_lb:
    image: nginx:latest
    volumes:
      - ./nginx-config/app-lb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/app-lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    restart: unless-stopped
    volumes:
      - ./proxy-data:/data
      - ./letsencrypt:/etc/letsencrypt
